server:
  port: 8070
  tomcat:
    connection-timeout: 10000
  servlet:
    session:
    timeout: 30s
spring:
  application:
    name: Weather-Forecast-API-App

weatherbit:
  base-url: https://api.weatherbit.io/v2.0
  api-key: ${WEATHERBIT_API_KEY}
  timeout-ms: 5000
